site_name: Learning content example

theme:
  name: material
  features:
    - content.code.annotate


# Adding a Git repository URL would display a link to the repository.
# Subject to the configuration, it would also enable authorised users to edit the content.

# repo_url: https://github.com/PDLT-University-of-York/mkdocs-material-example
# repo_name: View the source


# These are extensions that can enable additional ways of presenting content.

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - pymdownx.arithmatex:
      generic: true


# A range of plugins are available for MkDocs. In this example the search option has been enabled.
# The pdf-export plugin requires some additional Python libraries to be installed. When enabled a PDF would be generated
# every time the site was 'built'.

plugins:
  - search
#  - pdf-export


# For this sample, some additional javascript has been added to allow mathematical content 
# to be displayed.
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js